name: CI/CD for SPFx Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Package the solution
      run: gulp package-solution --ship

    - name: Upload SharePoint package
      uses: actions/upload-artifact@v4
      with:
        name: spfx-solution
        path: ./sharepoint/solution/modern-page-comments.sppkg

  - name: Debug environment variables
      run: |
        echo "SPO_SITE_URL: ${{ secrets.SPO_SITE_URL }}"
        echo "SPO_CLIENT_ID: ${{ secrets.SPO_CLIENT_ID }}"
        echo "SPO_CLIENT_SECRET: ${{ secrets.SPO_CLIENT_SECRET }}"

    - name: Deploy to SharePoint Online
      env:
        SPO_SITE_URL: ${{ secrets.SPO_SITE_URL }}
        SPO_CLIENT_ID: ${{ secrets.SPO_CLIENT_ID }}
        SPO_CLIENT_SECRET: ${{ secrets.SPO_CLIENT_SECRET }}
      run: |
        npm install -g @pnp/cli-microsoft365
        m365 login --authType password --userName $SPO_CLIENT_ID --password $SPO_CLIENT_SECRET
        m365 spo app add --filePath sharepoint/solution/advanced-comments-box.sppkg --appCatalogUrl $SPO_SITE_URL --overwrite
        m365 spo app deploy --name advanced-comments-box.sppkg --appCatalogUrl $SPO_SITE_URL --skipFeatureDe
